### ISSUE TITLE
Question: fedi.buzz user-agents

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [astro/buzzrelay#13]
What's the difference between the fedi.buzz user-agents. 

`caveman-hunter/0.0.0 (+https://fedi.buzz/)}`

`buzzrelay/0.1.0 (+https://relay.fedi.buzz)`

Are they different systems, or serving different purposes?

**Comment by astro** [comment]
caveman is what gathers the firehose, buzzrelay is just the relay but it doesn't gather the content.
