### ISSUE TITLE
Actor JSON-LD context is invalid

### ISSUE THREAD

**Issue by zotanmew** [astro/buzzrelay#17]
Heya, I just noticed that your JSON-LD payload for the Actor is invalid, specifically it's missing the w3id-security context (`https://w3id.org/security/v1`). This prevents federation with JSON-LD compliant AP implementations, as the publicKey field will deserialize to `_:publicKey` instead of `https://w3id.org/security#publicKey`. You can validate whether your context correctly deserializes by using tools like https://transform.tools/jsonld-to-expanded.

**Comment by astro** [comment]
Thank you for reporting!
