### ISSUE TITLE
Misskey fails to subscribe to custom buzzrelay instances

### ISSUE THREAD

**Issue by Ninlives** [astro/buzzrelay#3]
# Problem

Subscribe to custom buzzrelay instances from Misskey always fail with:
```
failed(UnrecoverableError: 400 Bad Request)
```

# Findings

It turns out that the 400 error is caused by a `SignatureFail` returned from https://github.com/astro/buzzrelay/blob/427acb073172f8db27694ef099c6cc848c32ff24/src/endpoint.rs#L116

The following patch works for me, but since I have not written any rust before, I actually don't know why the original code fail:
```patch
diff --git a/src/endpoint.rs b/src/endpoint.rs
index c0b2b00..bc32e76 100644
--- a/src/endpoint.rs
+++ b/src/endpoint.rs
@@ -112,10 +112,9 @@ impl<'a> Endpoint<'a> {
             authorized_fetch(client, &self.remote_actor_uri, key_id, private_key).await?
         )?;
         let public_key = PublicKey::from_pem(remote_actor.public_key.pem.as_bytes())?;
-        if ! (self.signature.verify(&public_key)?) {
-            return Err(Error::SignatureFail);
+        match self.signature.verify(&public_key) {
+            Ok(_) => Ok(remote_actor),
+            Err(_) => Err(Error::SignatureFail)
         }
-
-        Ok(remote_actor)
     }
 }
```
Again, I don't write rust, so I don't know if this patch fixed the problem or made the verification useless.

**Comment by astro** [comment]
I am sorry but your patch disables signature verification. Try this for comparison:

```patch
diff --git a/src/endpoint.rs b/src/endpoint.rs
index c0b2b00..bc32e76 100644
--- a/src/endpoint.rs
+++ b/src/endpoint.rs
@@ -112,10 +112,9 @@ impl<'a> Endpoint<'a> {
             authorized_fetch(client, &self.remote_actor_uri, key_id, private_key).await?
         )?;
         let public_key = PublicKey::from_pem(remote_actor.public_key.pem.as_bytes())?;
-        if ! (self.signature.verify(&public_key)?) {
-            return Err(Error::SignatureFail);
+        match self.signature.verify(&public_key) {
+            Ok(true) => Ok(remote_actor),
+            Ok(false) => Err(Error::SignatureFail),
+            Err(e) => Err(e.into()),
         }
-
-        Ok(remote_actor)
     }
 }
```

---

Misskey isn't quickly installable on NixOS yet. If anyone wants to help me debugging this, email me admin account credentials to a Misskey test instance.

**Comment by Ninlives** [comment]
That's embarrassing :( Here is a simple flake I used to run my instance.

**Comment by CustardFlan** [comment]
> I am sorry but your patch disables signature verification. Try this for comparison:
> 
> ```diff
> diff --git a/src/endpoint.rs b/src/endpoint.rs
> index c0b2b00..bc32e76 100644
> --- a/src/endpoint.rs
> +++ b/src/endpoint.rs
> @@ -112,10 +112,9 @@ impl<'a> Endpoint<'a> {
>              authorized_fetch(client, &self.remote_actor_uri, key_id, private_key).await?
>          )?;
>          let public_key = PublicKey::from_pem(remote_actor.public_key.pem.as_bytes())?;
> -        if ! (self.signature.verify(&public_key)?) {
> -            return Err(Error::SignatureFail);
> +        match self.signature.verify(&public_key) {
> +            Ok(true) => Ok(remote_actor),
> +            Ok(false) => Err(Error::SignatureFail),
> +            Err(e) => Err(e.into()),
>          }
> -
> -        Ok(remote_actor)
>      }
>  }
> ```
> 
> Misskey isn't quickly installable on NixOS yet. If anyone wants to help me debugging this, email me admin account credentials to a Misskey test instance.

After aplying this patch, misskey still refuses to load the activity, but now, with a new error:

`0|Misskey  | WARN 1	[queue inbox]	failed(UnrecoverableError: skip: signerHost(mybuzzhost.li) !== activity.id host(mastodon.social) id=1625 attempts=1/8 age=684ms activity=https://mastodon.social/@AmyDentata/110601337891924938
0|Misskey  | WARN 1	[queue inbox]	failed(UnrecoverableError: skip: signerHost(mybuzzhost.li) !== activity.id host(mastodon.social) id=1626 attempts=1/8 age=9ms activity=https://mastodon.social/@AmyDentata/110601337891924938
0|Misskey  | WARN 1	[queue inbox]	failed(UnrecoverableError: skip: signerHost(mybuzzhost.li) !== activity.id host(mastodon.social) id=1627 attempts=1/8 age=8ms activity=https://mastodon.social/@AmyDentata/110601337891924938
0|Misskey  | WARN 1	[queue inbox]	failed(UnrecoverableError: skip: signerHost(mybuzzhost.li) !== activity.id host(mastodon.social) id=1628 attempts=1/8 age=664ms activity=https://mastodon.social/@AmyDentata/110601337891924938
0|Misskey  | WARN 1	[queue inbox]	failed(UnrecoverableError: skip: signerHost(mybuzzhost.li) !== activity.id host(mastodon.social) id=1629 attempts=1/8 age=360ms activity=https://mastodon.social/@AmyDentata/110601337891924938
0|Misskey  | WARN 1	[queue inbox]	failed(UnrecoverableError: skip: signerHost(mybuzzhost.li) !== activity.id host(mastodon.social) id=1630 attempts=1/8 age=7ms activity=https://mastodon.social/@Alexmak/110601164720364559`

Pleroma still nothing, as usual, the logs show the request, but the notes never appear

**Comment by Ninlives** [comment]
For anyone who encountered same problem:
If you are serving buzzrelay behind nginx, don't forget to add the following config:
```
proxy_set_header        Host $host;
```
Other reverse proxy server should have similar options.
