### ISSUE TITLE
Follow posts by #tag does not support non alphabetic languages?

### ISSUE THREAD

**Issue by cherishmey** [astro/buzzrelay#5]
When any non-latin alphabet is used as a tag, the relay endpoint won't work;

![image](https://github.com/astro/buzzrelay/assets/26625558/3dffa0d7-05ae-4837-9943-b0e576dae1ea)

For example, if I want to use "톳친소" (similar to #introduction in Korean), the created endpoint(https://relay.fedi.buzz/tag/%ED%86%B3%EC%B9%9C%EC%86%8C) contains the following:

```
{"@context":"https://www.w3.org/ns/activitystreams","type":"Service","id":"https://relay.fedi.buzz/tag/toscinso","name":"#toscinso","icon":{"type":"Image","mediaType":"image/jpeg","url":"https://fedi.buzz/assets/favicon48.png"},"inbox":"https://relay.fedi.buzz/tag/toscinso","publicKey":{"id":"https://relay.fedi.buzz/tag/toscinso#key","owner":"https://relay.fedi.buzz/tag/toscinso","publicKeyPem":"-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvmdr++5uIBM4KiLdV11E\n38WbkpbmfvlSM2fF3IJf7apZvjDYeUnm10L7vfC7Fy6bk+ljIpzOUamfpgLOKI51\nssz/FIWhT+C8SeP37eQxOMTZclLpj9ef/zC8wJ6zvZPdCA2dJl6x9VSwn7EkBv/6\n4r79/BiW4P0khiSSheONTxcPgZo6m1MZCFnlqoSZIW2OJIp346721VxZb+c9Wqgd\npKHd9jNN7n6LTWwf0vdRD9lYs+cXmlo+2fuZJoSEXRif8mo6WQ4Ui4z9QuGUodFL\nrYuXuhOjGElIYw3IXMPm2w3LsAG6O1xDMdP9whd3mkuH/ceH7JK1/Zbi3ChnT/1f\nFDaSSPhxuiPsm97YhGrH6HgSkmlwn43+vqcfEBA00j06rn6JpoIiZHGtsMAjfGOy\nZtZ1qD15EVeavhm2qRfCVKWbIf2RE5sHOYyjWbNYDxckRhSuGMwjIQk/XYyie5yM\noxHq4xIlitRfxt84Eq0NuykTZgK1zv7DvjgfGnrcDWcnTo69pdMN4k0K5xpNJuE/\nCIMtYCBoCOabCIo8bnUAPj/9shcI8GTqYmr1VdI9n2XiO05iFekDcYfYgGszIjMS\nS3z9A8g1VE/ITWW9SlGfaTRhKfZsHaMpg/fNbk/G7SjYOghsy3qdX/rvwPIr+tti\n/AJz1hrO5vndr0YxcYk1jU0CAwEAAQ==\n-----END PUBLIC KEY-----\n"},"preferredUsername":"tag-toscinso"}
```

so the problem is that 톳친소 is automatically converted to toscinso(from the pronounciation, I guess).

**Comment by astro** [comment]
This is [intentionally](https://github.com/astro/buzzrelay/blob/main/src/actor.rs#L15) as we need to map it into a username which doesn't allow non-ASCII chars. It should still work... what is your instance?

**Comment by cherishmey** [comment]
Oh it works now. Maybe it was an internal issue and I was being too hasty (My instance had issues with other relays)? Sorry to bother you... and thanks for the awesome work.
